# Generated by Django 3.1.4 on 2021-03-18 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeAdminModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_admin_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='o_admin_name', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
